### ISSUE TITLE
1-band imagery IoU error

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/doodleverse_utils#10]
I am attempting to test the new loss functions with 1-band imagery. I fetched new updates from `main` and updated `doodleverse_utlis==0.0.5`. After running `train_model.py`, I receive the following error:

```
(gym) cbodine@filfy-Thelio-Massive:~/PythonRepos/segmentation_gym$ python train_model.py 
2022-10-04 08:27:48.844598: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/mnt/md0/SynologyDrive/Modeling/Substrate_BOU-LEA_5_remapHard/03_forModelTraining/dataset
/mnt/md0/SynologyDrive/Modeling/Substrate_BOU-LEA_5_remapHard/03_forModelTraining/config/substrate_20221004_v7.json
Using GPU
Using single GPU device
Version:  2.10.0
Eager mode:  True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Making new directory for example model outputs: /mnt/md0/SynologyDrive/Modeling/Substrate_BOU-LEA_5_remapHard/03_forModelTraining/modelOut
MODE "all": using all augmented and non-augmented files
2022-10-04 08:28:46.128074: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-04 08:28:46.862641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14597 MB memory:  -> device: 0, name: Quadro RTX 5000, pci bus id: 0000:65:00.0, compute capability: 7.5
369
221
.....................................
Creating and compiling model ...
.....................................
Training model ...

Epoch 1: LearningRateScheduler setting learning rate to 1e-07.
Epoch 1/100
Traceback (most recent call last):
  File "/home/cbodine/PythonRepos/segmentation_gym/train_model.py", line 721, in <module>
    history = model.fit(train_ds, steps_per_epoch=steps_per_epoch, epochs=MAX_EPOCHS,
  File "/home/cbodine/anaconda3/envs/gym/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filekmiiz2fb.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/__autograph_generated_file0km3dfxo.py", line 27, in tf__mean_iou
    ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(nclasses),), None, fscope), None, loop_body, get_state, set_state, ('iousum',), {'iterate_names': 'index'})
  File "/tmp/__autograph_generated_file0km3dfxo.py", line 25, in loop_body
    iousum += ag__.converted_call(basic_iou, (y_true[:, :, :, index], y_pred[:, :, :, index]), None, fscope)
ValueError: in user code:

    File "/home/cbodine/anaconda3/envs/gym/lib/python3.10/site-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/home/cbodine/anaconda3/envs/gym/lib/python3.10/site-packages/doodleverse_utils/model_imports.py", line 989, in mean_iou  *
        iousum += basic_iou(y_true[:,:,:,index], y_pred[:,:,:,index])

    ValueError: slice index 4 of dimension 3 out of bounds. for '{{node strided_slice_11}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=7, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=8](one_hot, strided_slice_11/stack, strided_slice_11/stack_1, strided_slice_11/stack_2)' with input shapes: [?,512,512,4], [4], [4], [4] and with computed input tensors: input[1] = <0 0 0 4>, input[2] = <0 0 0 5>, input[3] = <1 1 1 1>.
```

_Originally posted by @CameronBodine in https://github.com/Doodleverse/doodleverse_utils/issues/8#issuecomment-1267196682_

**Comment by ebgoldstein** [comment]
@CameronBodine - can you post your config here?

**Comment by CameronBodine** [comment]
```
{
  "TARGET_SIZE": [512,512],
  "MODEL": "resunet",
  "NCLASSES": 5,
  "KERNEL":9,
  "STRIDE":2,
  "BATCH_SIZE": 34,
  "FILTERS":6,
  "N_DATA_BANDS": 1,
  "DROPOUT":0.05,
  "DROPOUT_CHANGE_PER_LAYER":0.0,
  "DROPOUT_TYPE":"standard",
  "USE_DROPOUT_ON_UPSAMPLING":false,
  "DO_TRAIN": true,
  "LOSS":"dice",
  "PATIENCE": 10,
  "MAX_EPOCHS": 100,
  "VALIDATION_SPLIT": 0.6,
  "RAMPUP_EPOCHS": 20,
  "SUSTAIN_EPOCHS": 0.0,
  "EXP_DECAY": 0.9,
  "START_LR":  1e-7,
  "MIN_LR": 1e-7,
  "MAX_LR": 1e-4,
  "FILTER_VALUE": 0,
  "DOPLOT": true,
  "ROOT_STRING": "substrate_5",
  "USEMASK": true,
  "AUG_ROT": 0,
  "AUG_ZOOM": 0.00,
  "AUG_WIDTHSHIFT": 0.05,
  "AUG_HEIGHTSHIFT": 0.00,
  "AUG_HFLIP": true,
  "AUG_VFLIP": false,
  "AUG_LOOPS": 10,
  "AUG_COPIES": 3,
  "TESTTIMEAUG": false,
  "SET_GPU": "0",
  "MODE": "all"
}
```

**Comment by ebgoldstein** [comment]
I don;t know what the problem nor the solution is, but presumably somehow the tensor shape is not right after it comes out of the onehot-argmax line (L987).. 

I am not familiar with one band images at all, and what the tensor shape looks like as it transits the network, but i think it should have slice index of up to `NCLASSES` in dimension *4* of your tensor.. but the code is trying to slice dim 3... :thinking: 

https://github.com/Doodleverse/doodleverse_utils/blob/3e703b0ddaca454010c6657195d4fa2573701c8e/doodleverse_utils/model_imports.py#L953-L993

**Comment by CameronBodine** [comment]
Ok, I will dig in and see if I can figure out a solution and will update with any findings.  Thanks!

**Comment by ebgoldstein** [comment]
@CameronBodine - very sorry it is broken for you.. i should have tested on 1 band images..

I will say that for me, when testing + development, i put the IoU code in gym, specifically in `train_model.py`  ~ line 500, using the exact same function names. This is below the Doodleverse_utils import at Line 117, so it worked as a way to test reformulations of the functions quickly.. (then i put the implementations that worked back into doodleverse_utils later..)

I can also help test, let me know.. if you want help, can you email me 5-10 images + labels? (and i will use your config from above)

**Comment by dbuscombe-usgs** [comment]
Same error for me. 3-band imagery. 9 classes. Also tried a 3-band image + NCLASSES=1

**Comment by ebgoldstein** [comment]
i think i see the issue.. its line 987... its hard-coded for 4 class imagery... 
`y_pred = tf.one_hot(tf.argmax(y_pred, -1), 4) `
should be y_pred = tf.one_hot(tf.argmax(y_pred, -1), NCLASSES)

**Comment by ebgoldstein** [comment]
(note the lower case `nclasses`... )

**Comment by CameronBodine** [comment]
> i think i see the issue.. its line 987... its hard-coded for 4 class imagery... `y_pred = tf.one_hot(tf.argmax(y_pred, -1), 4) ` should be `y_pred = tf.one_hot(tf.argmax(y_pred, -1), nclasses)` my bad!

Made the above fix, and model is now training!

**Comment by dbuscombe-usgs** [comment]
I'll ready a new doodleverse-utils with the fix. First, I will check a few more data band and nclass combos, with all available losses, just to be sure

**Comment by dbuscombe-usgs** [comment]
same dataset (nbands=3,nclasses=9 ), this time using 'cat' loss ...

```
    ValueError: slice index 4 of dimension 3 out of bounds. for '{{node strided_slice_11}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=7, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=8](one_hot, strided_slice_11/stack, strided_slice_11/stack_1, strided_slice_11/stack_2)' with input shapes: [?,768,768,4], [4], [4], [4] and with computed input tensors: input[1] = <0 0 0 4>, input[2] = <0 0 0 5>, input[3] = <1 1 1 1>.
```

so I guess there is something wrong with `model.compile(optimizer = 'adam', loss =tf.keras.losses.CategoricalCrossentropy(), metrics = [iou_multi(NCLASSES), dice_multi(NCLASSES)])`. I'll do some digging

**Comment by ebgoldstein** [comment]
@dbuscombe-usgs , this looks like the same sort of Tensor shape error (IoU, and not from `CCE`).. where its one-hot encoding the images into 4 classes:

> ....with input shapes: [?,768,768,4]

So i am wondering if a change you made just didn't stick?

**Comment by ebgoldstein** [comment]
:thinking:

**Comment by dbuscombe-usgs** [comment]
deleted model, remade, then compiled with `model.compile(optimizer = 'adam', loss =tf.keras.losses.KLDivergence())`

now the error is

```
InvalidArgumentError:  required broadcastable shapes
         [[node kl_divergence/truediv (defined at <ipython-input-35-7ee677347b23>:1) ]] [Op:__inference_train_function_44183]
```

No idea why the recent changes would create this behaviour

**Comment by dbuscombe-usgs** [comment]
This turns out to be operator error. I had specified NCLASSES=9, but it turns out the correct one is NCLASSES=10 .... model now trains using `model.compile(optimizer = 'adam', loss =tf.keras.losses.CategoricalCrossentropy(), metrics = [iou_multi(NCLASSES), dice_multi(NCLASSES)])`

however, this opens some new issues that I will explain below

I troubleshooted this by first checking my tensor dimensions

```
    for counter, (imgs,lbls) in enumerate(train_ds.take(1)):
        for count,(im,lab) in enumerate(zip(imgs, lbls)):
            print(im.shape)
```

which outputs (768,768,10). That's how I knew what NCLASSES to use. But this presents two problems:

1. the specification of NCLASSES in the config file, at least for training, may not be necessary, and could lead to problems if incorrectly specified, like I did. I suppose the issue was that the image padding adds a 'null' (zero) class .... 
2. the new dice loss doesn't check for cardinality issues. It will train with NCLASSES=9, even though there are 10

**Comment by dbuscombe-usgs** [comment]
To address 1. above, padding could be removed from make_datasets and an alternative implemented, i.e. simple resizing

I also think it is a good idea to modify `train_model.py` so `NCLASSES` is ignored, and reads it from the data, i.e.

```
    for counter, (imgs,lbls) in enumerate(train_ds.take(1)):
        for count,(im,lab) in enumerate(zip(imgs, lbls)):
            NCLASSES = lab.shape[-1]
```

this would avoid operator error associated with specifying NCLASSES in training

**Comment by dbuscombe-usgs** [comment]
Bug fix implemented in https://pypi.org/project/doodleverse-utils/ version 0.0.6

In an activate `gym` env, update using `pip install doodleverse-utils -U`
