### ISSUE TITLE
Add support for 1-band imagery in `do_seg()` for segformer

### ISSUE THREAD

**Issue by CameronBodine** [Doodleverse/doodleverse_utils#24]
Similar to [this issue](https://github.com/Doodleverse/segmentation_gym/issues/115#issuecomment-1428847537), the `do_seg()` function needs to be updated to support segmentation on 1-band imagery when using `segformer`.

Change this:
https://github.com/Doodleverse/doodleverse_utils/blob/83128ee3e7a8dd901415c6f00145f31b8c44bb02/doodleverse_utils/prediction_imports.py#L169-L170

and this:

https://github.com/Doodleverse/doodleverse_utils/blob/83128ee3e7a8dd901415c6f00145f31b8c44bb02/doodleverse_utils/prediction_imports.py#L306-L307

to:
```
if MODEL=='segformer':
            if N_DATA_BANDS == 1:
                image = np.dstack((image, image, image))
            image = tf.transpose(image, (2, 0, 1))
```

Note: there is no need to use `tf.concat` as `image` is already an `ndarray`, allowing the use of `np.dstack()`.

**Comment by dbuscombe-usgs** [comment]
Excellent, thanks. I have made this change in the latest push

**Comment by dbuscombe-usgs** [comment]
[git clean -xfd](https://pypi.org/project/doodleverse-utils/0.0.24/)

**Comment by CameronBodine** [comment]
Ooops, I messed up. What I proposed above works when the inputs are `npz` but not `jpg` or `png`.  When the image is standardized here

https://github.com/Doodleverse/doodleverse_utils/blob/fd884a7ef40f76f862449405d430fcc41cd10887/doodleverse_utils/prediction_imports.py#L167

or here

https://github.com/Doodleverse/doodleverse_utils/blob/fd884a7ef40f76f862449405d430fcc41cd10887/doodleverse_utils/prediction_imports.py#L291

the function will create a three-band image if the number of dimensions is 2 as shown here

https://github.com/Doodleverse/doodleverse_utils/blob/fd884a7ef40f76f862449405d430fcc41cd10887/doodleverse_utils/imports.py#L153-L154

However, if the input is an `npz` exported from `make_nd_datasets.py`, it will have three dimensions, even if it is a 1-band array as in `(h, w, 1)`. But, if the input is a `jpg` or `png`, the number of dimensions will be 2, and the `standardize` function will create a 3-dimension array. Since the fix is using `N_DATA_BANDS` instead of the number of dimensions, the `dstack` will create a 9-band raster (3x3-band rasters stacked). I recommend changing this

https://github.com/Doodleverse/doodleverse_utils/blob/fd884a7ef40f76f862449405d430fcc41cd10887/doodleverse_utils/prediction_imports.py#L170

and this

https://github.com/Doodleverse/doodleverse_utils/blob/fd884a7ef40f76f862449405d430fcc41cd10887/doodleverse_utils/prediction_imports.py#L294

to this:
```
if np.ndim(image)==2:
```

Sorry for the mix-up!

**Comment by dbuscombe-usgs** [comment]
Thanks, I can update `do_seg`

**Comment by dbuscombe-usgs** [comment]
Implemented in https://pypi.org/project/doodleverse-utils/0.0.25/
