### ISSUE TITLE
doodleverse_utils should have more than one manager on pypi.org

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/doodleverse_utils#4]
I am the sole maintainer and administrator of `doodleverse_utils`. I propose we add at least one more person who can upload new versions

```
There are two possible roles for collaborators:

Maintainer
    Has permissions to Upload releases for a package. Can upload releases. Cannot invite collaborators. Cannot delete files, releases, or the project.
Owner
    Has permissions to Administer the entire project. Can upload releases. Can invite other collaborators. Can delete files, releases, or the entire project. 
```

I propose adding @ebgoldstein and/or @2320sharon as a new 'Maintainer', which requires having a pypi account. Not a priority but leaving here as a reminder

**Comment by dbuscombe-usgs** [comment]
How to update the `doodleverse-utils` pypi package

First, submit your local changes to github the usual way (git add/commit/push)

Second, on github, create a new release

Third, locally

```
git fetch
git checkout nameoftag (e.g. v0.0.1-beta)
python setup.py sdist bdist_wheel
twine upload dist/* --verbose
git switch -
git clean -xfd
```

**Comment by ebgoldstein** [comment]
that works for me... i made these instructions a [wiki page](https://github.com/Doodleverse/doodleverse_utils/wiki/Updating-doodleverse-utils-on-pypi)
